### ISSUE TITLE
Error: spawn testrpc ENOENT

### ISSUE THREAD

**Issue by ghost** [gnosis/run-with-testrpc#1]
from docker tag node:7.10-wheezy

getting this error:

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn testrpc ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
The command '/bin/sh -c ./node_modules/.bin/run-with-testrpc 'truffle migrate'' returned a non-zero code: 1

**Comment by cag** [comment]
Whoa, just noticed this ;_;

I just got a similar error in this build: https://travis-ci.org/gnosis/gnosis-contracts/jobs/269737126

**Comment by cag** [comment]
Thanks for reporting, and please feel free to reopen this if the issue was actually different.
